jewelGleamer/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'jewelGleamer'
urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.logged_user_home, name='logged_user_home'),
    path('blog/', views.blog, name='blog'),
    path('other_blogs/', views.other_blogs, name='other_blogs'),
    path('items/', views.jewelry_items_list, name='items_list'),
    path('items/<int:item_id>', views.jewelry_item_detail, name='item_detail'),
    path('items/<int:item_id>/delete_review/<int:review_id>/', views.delete_review, name='delete_review'),
    path('items/search', views.search, name='search'),
    path('items/add/', views.add_item, name='add_item'),
    path('items/<int:ring_id>/delete/', views.delete_ring, name='delete_ring'),
    path('items/<int:ring_id>/edit', views.edit_ring, name='edit_ring'),
    path('items/add_item/', views.add_new_item, name='add_new_item'),
    path('items/<int:item_id>/edit_review/<int:review_id>/', views.edit_review, name='edit_review'),
    path('generate_description/<int:item_id>/', views.generate_description, name='generate_description'),
    path('save_description/<int:item_id>/', views.save_description, name='save_description'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jewelGleamers/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jewelGleamer.urls', namespace='jewelGleamer')),
    path('users/', include('users.urls', namespace='users')),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('register', views.register, name='register'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('login_page',views.login_page, name="login_page"),
    path('userprofiles/', views.user_profiles, name='user_profiles'),
]

jewelGleamer/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


# Product class on the category page
class Product(models.Model):
    name = models.CharField(max_length=200)
    price = models.IntegerField(default=0)
    url = models.ImageField(upload_to='images/')
    author = models.CharField(default='Sindhu')
    date_posted = models.DateTimeField(default=timezone.now)
    details = models.TextField(default='Made in 14k solid gold, the alloy gives our pieces its beautiful, subtle hue. '
                                       'Band Thickness: 1.0 mm')
    description = models.TextField(default='The Stacker is the white tee of rings. It is everyone go-to because there '
                                           'is nothing it cant go with. This 14k solid gold essential is the perfect '
                                           'starter ring or addition to anyone collection.')
    materials = models.TextField(default='14k Solid Gold Our 14k solid gold pieces are made to last forever. 14k gold '
                                         'will not oxidize or discolor, so you can wear your jewelry every day.')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('jewelGleamer:item_detail', args=[self.id])


class Blogs(models.Model):
    description = models.TextField()


# Review Class
class Review(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    item = models.ForeignKey(Product, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.item.name

    def get_absolute_url(self):
        return reverse('jewelGleamer:item_detail', args=[self.item_id])


# Item Class for detailed view
class Item(models.Model):
    name = models.CharField(max_length=200)
    price = models.IntegerField(default=0)
    details = models.TextField()
    description = models.TextField()
    materials = models.TextField()
    urls = models.TextField()


# Image Class for urls
class Images(models.Model):
    url = models.CharField(max_length=200)


admin_user = {"username": "Admin", "password": "Admin"}
regular_user = {"username": "Sindhu", "password": "Sindhu"}

jewelGleamer/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['title', 'content']

jewelGleamer/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.urls import reverse
from .models import Review, Images, Product, Blogs
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from .forms import ReviewForm
from actions.models import Action
import openai
import random
import logging

openai.api_key = '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'


# Navigation to the home page when the user did not login to the page
def home(request):
    return render(request, "jewelGleamer/jewelry/index.html")


# Navigation to the home page when the user is logged in
def logged_user_home(request):
    image_list = Images.objects.all()
    actions = Action.objects.all().order_by('-created')
    return render(request, "jewelGleamer/jewelry/alternate.html",
                  {"images": image_list, "actions": actions})


# List of items in the item page
def jewelry_items_list(request):
    product_list = Product.objects.all().order_by('id')
    return render(request, "jewelGleamer/jewelry/category.html",
                  {"rings": product_list})


# Every item detail page
def jewelry_item_detail(request, item_id):
    item = get_object_or_404(Product, id=item_id)
    review_list = list(Review.objects.filter(item=item_id).order_by('-date_posted'))
    if request.method == 'POST':
        username = request.session.get('username')
        user = User.objects.get(username=username)
        content = request.POST.get('content', '')
        title = request.POST.get('title', '')
        review = Review.objects.create(author=user, title=title, content=content, item=item)
        review_title = review.title
        review_list.append(review)
        # log the action
        action = Action(
            user=user,
            verb="created a review " + review_title + " for the product ",
            target=item
        )
        action.save()

    review_list = Review.objects.filter(item=item_id).order_by('-date_posted')
    return render(request, "jewelGleamer/jewelry/item.html",
                  {"reviews": review_list, "item": item})


def edit_review(request, review_id, item_id):
    review = get_object_or_404(Review, id=review_id)
    review_title = review.title
    user = User.objects.get(username=request.session.get('username'))
    if request.method == 'POST':
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            form.save()
            # log the action
            action = Action(
                user=user,
                verb="edited a review with title " + review.title + " for the product",
                target=review
            )
            action.save()
            return redirect('jewelGleamer:item_detail', item_id=review.item.id)
    else:
        form = ReviewForm(instance=review)
    return render(request, "jewelGleamer/jewelry/edit_review.html", {"form": form, "review": review})


def delete_review(request, review_id, item_id):
    user = User.objects.get(username=request.session.get('username'))
    review = get_object_or_404(Review, id=review_id)
    review_title = review.title
    if request.session.get('username') == review.author.username or request.session.get('role') == 'Admin':
        # log the action
        action = Action(
            user=user,
            verb="deleted a review " + review_title,
            target=review
        )
        action.save()
        review.delete()
    return JsonResponse({'success': True, 'deleted_review_id': review_id})


# Adding an item to the category page of a product
def add_item(request):
    if request.method == 'POST':
        item_name = request.POST.get('item_name')
        item_price = request.POST.get('item_price')
        item_url = request.FILES['item_url'] if 'item_url' in request.FILES else None
        item_details = request.POST.get('item_details')
        item_description = request.POST.get('item_description')
        item_materials = request.POST.get('item_materials')
        user = User.objects.get(username=request.session.get('username'))
        new_product = Product(
            name=item_name,
            price=item_price,
            author=request.session.get('username'),
            details=item_details,
            description=item_description,
            materials=item_materials
        )
        product_name = new_product.name
        if item_url:
            new_product.url = item_url
        new_product.save()
        # log the action
        action = Action(
            user=user,
            verb="created a new product "+product_name+" : Link - ",
            target=new_product
        )
        action.save()
        messages.add_message(request, messages.SUCCESS, "You have successfully added product: %s" % new_product.name)
        return redirect('jewelGleamer:item_detail', item_id=new_product.id)
    product_list = Product.objects.all()
    return render(request, 'jewelGleamer/jewelry/category.html', {'rings': product_list})


# Deleting an item from the category page of a product
def delete_ring(request, ring_id):
    try:
        user = User.objects.get(username=request.session.get('username'))
        item_to_delete = Product.objects.get(id=ring_id)
        # log the action
        action = Action(
            user=user,
            verb="deleted the product : " + item_to_delete.name,
            target=item_to_delete
        )
        action.save()
        item_to_delete.delete()
        messages.add_message(request, messages.WARNING,
                             "You have successfully deleted product: %s" % item_to_delete.name)
    except Product.DoesNotExist:
        pass
    return redirect('jewelGleamer:items_list')


# Blog page view of the page where user can find other users blog
def blog(request):
    blogs_list = Blogs.objects.all()
    return render(request, "jewelGleamer/jewelry/blog.html", {"blogs": blogs_list})


# Searching the search bar on the header to navigate to the respective page
def search(request):
    search_input = request.GET.get('search-input', '').lower()
    product_list = Product.objects.all()
    blogs_list = Blogs.objects.all()
    if search_input == 'rings':
        return render(request, 'jewelGleamer/jewelry/category.html', {"rings": product_list})
    elif search_input == 'blogs':
        return render(request, 'jewelGleamer/jewelry/blog.html', {"blogs": blogs_list})
    else:
        return render(request, 'jewelGleamer/jewelry/search.html')


# Edit view to change item name and price on the category page for the product
def edit_ring(request, ring_id):
    product_list = Product.objects.get(id=ring_id)
    user = User.objects.get(username=request.session.get('username'))
    if request.method == 'POST':
        old_name = product_list.name
        old_price = product_list.price
        new_name = request.POST.get('new_name')
        new_price = request.POST.get('new_price')
        new_details = request.POST.get('new_details')
        new_description = request.POST.get('new_description')
        new_materials = request.POST.get('new_materials')
        if old_name != new_name:
            action_title = f"edited the title from '{old_name}' to '{new_name}': Link - "
            product_list.name = new_name
            action_title_instance = Action(
                user=user,
                verb=action_title,
                target=product_list
            )
            action_title_instance.save()
        if int(old_price) != int(new_price):
            action_price = f"edited the price from {old_price} to {new_price} : Link - "
            product_list.price = new_price
            action_price_instance = Action(
                user=user,
                verb=action_price,
                target=product_list
            )
            action_price_instance.save()
        product_list.name = new_name
        product_list.price = new_price
        product_list.details = new_details
        product_list.description = new_description
        product_list.materials = new_materials
        product_list.save()
        messages.add_message(request, messages.INFO, "You have successfully edited product: %s" % old_name)
        item_detail_url = reverse('jewelGleamer:item_detail', kwargs={'item_id': ring_id})
        return HttpResponseRedirect(item_detail_url)
    return render(request, 'jewelGleamer/jewelry/edit_product.html', {'product': product_list})


# Retrieving other blog posts in the blog page
def other_blogs(request):
    blogs = Blogs.objects.all()
    other_blog = [{'description': b.description} for b in blogs]
    return JsonResponse({'blogs': other_blog})


# Adding new item in the category page
def add_new_item(request):
    return render(request, 'jewelGleamer/jewelry/add_item.html')


# Generating AI related description for a product using description and materials.
def generate_description(request, item_id):
    try:
        item = get_object_or_404(Product, id=item_id)
        current_description = item.description
        item_details = item.details
        item_materials = item.materials
        prompt = request.POST.get('prompt', f"Provide an interesting description of the product: {current_description} using details: {item_details} and consider the item materials: {item_materials}. Limit the enhanced description to 2 lines please.")
        if not prompt:
            raise ValueError("Prompt cannot be empty.")
        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": "You are a helpful assistant."},
                {"role": "user", "content": prompt},
            ]
        )
        if 'choices' not in response or not response['choices']:
            raise ValueError("Failed to generate a description. Please try again.")
        choices = response['choices']

templates/jewelGleamer/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<!-- Base template to re-use for all the other html pages -->
<head>
    <title>JewelGleamers  | {% block page-title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="description" content="The homepage for JewelGleamers">
    <!--Social Media Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!--Linking the styling sheets-->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static "js/sort.js" %}"></script>
    <script src="{% static "js/script.js" %}"></script>
    <link rel="stylesheet" href="{% static "css/global.css" %}">
    <link rel="stylesheet" href="{% static "css/review.css" %}">
    <link rel="stylesheet" href="{% static "css/index.css" %}">
    <link rel="stylesheet" href="{% static "css/profile.css"%}">
    <link rel="stylesheet" href="{% static "css/alternate.css" %}">
    <link rel="stylesheet" href="{% static "css/blog.css" %}">
    <link rel="stylesheet" href="{% static "css/item.css" %}">
    <link rel="stylesheet" href="{% static "css/category.css" %}">
    <link rel="stylesheet" href="{% static "css/search.css" %}">
</head>

<!-- All the images used in the design are taken from Amazon, Ana Luisa websites -->

<body>
    <header class="header">
        <!-- Header of the page -->
        <div class="header-title">
            <!-- Adding the logo to the page -->
            <img class="logo" src="{% static "images/logo.png" %}" alt="Logo">
            <h1 class="header-website">JewelGleamers</h1>
        </div>
        <div class="header-search-bar">
            <!-- form input text to search the store -->
            <form action="{% url 'jewelGleamer:search' %}" method="get" class = "search-form">
    <input class="search-bar" type="text" placeholder="Search entire store here.." name="search-input" id="search-input">
    <button class="submit">Search</button>
</form>
        </div>
        <div class="header-icons">
            <!-- Header icons representing locations, wishlist, shopping cart and signin/login -->
            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
            <a class="sign-in" href="{% url "users:user_profiles" %}">User Profiles</a>
            {% if request.session.username %}
             <a href="{% url 'users:profile' request.session.username %}" class="sign-in">
                 {{request.session.username }}
             </a>
                <a class="sign-in" href="{% url 'users:logout'%}">Logout</a>
            {% else %}
                <a class="sign-in" href="{% url 'users:register'%}">Sign in / Sign up</a>
            {% endif %}
        </div>
    </header>
    <div class="main-content">
        <!-- Main content of the page -->
        <div class="top-navigation">
            <!-- Navigation bar to search the various types of jewelry -->
            {% if request.session.username %}
            <a href="{% url 'jewelGleamer:logged_user_home' %}">Home</a>
            {% else %}
            <a href="{% url 'jewelGleamer:home' %}">Home</a>
            {% endif %}
            <a href="{% url 'jewelGleamer:items_list' %}">Rings</a>
            <a href="{% url 'jewelGleamer:blog' %}">Blogs</a>
        </div>
      {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
        {% block main-content %}{% endblock %}
    </div>
    <footer class="footer">
        <!-- Footer of the page -->
        <div class="footer-nav">
            <!-- About us, Rate us and Contact us -->
            <a href="{% url 'jewelGleamer:home' %}">About</a>
            <a href="{% url 'jewelGleamer:home' %}">Rate Us</a>
            <a href="{% url 'jewelGleamer:home' %}">Contact Us</a>
        </div>
        <div class="copyrights">
            <!-- Copyrights, privacy and terms, conditions -->
            <a>© 2022 JewelGleamers Diamonds Corporation</a>
            <a href="{% url 'jewelGleamer:home' %}"> Privacy Policy </a>
            <a href="{% url 'jewelGleamer:home' %}">Terms & Conditions</a>
        </div>
        <div class="footer-icons">
            <!-- Footer social media icons -->
            <a href="https://www.facebook.com/" class="fa fa-facebook"></a>
            <a href="https://www.twitter.com/" class="fa fa-twitter"></a>
            <a href="https://www.instagram.com/" class="fa fa-instagram"></a>
        </div>
    </footer>
</body>

</html>