jewelGleamers/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jewelGleamer.urls', namespace='jewelGleamer')),
    path('users/', include('users.urls', namespace='users')),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('register', views.register, name='register'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('login_page',views.login_page, name="login_page"),
    path('userprofiles/', views.user_profiles, name='user_profiles'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Details(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(default="Regular", max_length=50)
    gender = models.CharField(default="other", max_length=25)


@receiver(post_save, sender=User)
def create_user_details(sender, instance, created, **kwargs):
    if created:
        Details.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_details(sender, instance, **kwargs):
    instance.details.save()

users/forms.py
from django import forms
from django.core.validators import RegexValidator
from django.contrib.auth.models import User


class RegistrationForm(forms.Form):
    username = forms.CharField(max_length=50, required=True)
    password = forms.CharField(widget=forms.PasswordInput, required=True,
                               min_length=5)
    email = forms.EmailField(max_length=50, required=True)

    first_name = forms.CharField(max_length=30, required=True, validators=[
        RegexValidator(r'^[a-zA-Z]*$', message="First name should not contain numerics")])
    last_name = forms.CharField(max_length=30, required=True, validators=[
        RegexValidator(r'^[a-zA-Z]*$', message="Last name should not contain numerics")])

    gender = forms.ChoiceField(
        choices=(("Male", "Male"), ("Female", "Female"), ("Other", "Other")),
        widget=forms.RadioSelect(),
        required=True,
    )


class ProfileForm(forms.Form):
    password = forms.CharField(widget=forms.TextInput(attrs={'type': 'password'}), required=True, min_length=5)
    email = forms.EmailField(max_length=50, required=True)
    first_name = forms.CharField(max_length=30, required=True, validators=[
        RegexValidator(r'^[a-zA-Z]*$', message="First name should not contain numerics, only alphabets")])
    last_name = forms.CharField(max_length=30, required=True, validators=[
        RegexValidator(r'^[a-zA-Z]*$', message="Last name should not contain numerics, only alphabets")])
    gender = forms.ChoiceField(
        choices=(("Male", "Male"), ("Female", "Female"), ("Other", "Other")),
        widget=forms.RadioSelect(),
        required=True,
    )
    role = forms.CharField(max_length=10, required=False)

users/views.py
from django.contrib import messages
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from .models import Details
from .forms import RegistrationForm, ProfileForm
from actions.models import Action


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            email = form.cleaned_data['email']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            user = User.objects.create(username=username, email=email, password=password, first_name=first_name,
                                       last_name=last_name)
            details, created = Details.objects.get_or_create(user=user)
            gender = form.cleaned_data['gender']
            details.gender = gender
            details.save()
            request.session['username'] = user.username
            request.session['role'] = details.role
            messages.success(request, f"You have successfully registered with username: {user.username}")
            return redirect('jewelGleamer:logged_user_home')
        else:
            messages.error(request, 'Registration failed. Please correct the errors below.')
    else:
        form = RegistrationForm()
    return render(request, "users/user/register.html", {'form': form})


def profile(request, username):
    user = get_object_or_404(User, username=username)
    if request.session.get('role') == 'Admin' or user.username == request.session.get('username'):
        if request.method == 'POST':
            form = ProfileForm(request.POST)
            if form.is_valid():
                user.password = form.cleaned_data['password']
                user.email = form.cleaned_data['email']
                user.first_name = form.cleaned_data['first_name']
                user.last_name = form.cleaned_data['last_name']
                gender = form.cleaned_data['gender']
                user.save()
                details, created = Details.objects.get_or_create(user=user)
                details.gender = gender
                if user.username != request.session.get('username'):
                    role = form.cleaned_data['role']
                    old_role = details.role
                    details.role = role
                details.save()
                if user.username != request.session.get('username'):
                    if old_role != form.cleaned_data['role']:
                        action = Action(
                            user=user,
                            verb="role changed from "+old_role+" to "+form.cleaned_data['role'],
                            role_changed=True,
                        )
                        action.save()
                messages.success(request, "You have updated the details successfully")
        else:
            form = ProfileForm(initial={
                'password': user.password,
                'email': user.email,
                'first_name': user.first_name,
                'last_name': user.last_name,
                'gender': user.details.gender if hasattr(user, 'details') else None,
                'role': user.details.role if hasattr(user, 'details') else None
            })
    else:
        actions = Action.objects.filter(user_id=user.id).order_by('-created')
        return render(request, 'users/user/profile.html', {"user": user, "actions": actions})
    actions = Action.objects.filter(user_id=user.id).order_by('-created')
    return render(request, 'users/user/profile.html', {"user": user, 'form': form,
                                                       "actions": actions})


def login_user(request):
    username = request.POST.get("username")
    password = request.POST.get("password")
    User = get_user_model()
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        user = None
    if user is not None and (password == user.password):
        request.session['username'] = user.username
        request.session['role'] = user.details.role
        messages.add_message(request, messages.SUCCESS, "You have logged in successfully")
        return redirect('jewelGleamer:logged_user_home')
    else:
        messages.add_message(request, messages.ERROR, "Invalid Username or Password")
    return render(request, 'users/user/login.html')


# Logout View
def logout_user(request):
    del request.session['username']
    del request.session['role']
    return redirect('jewelGleamer:home')


def login_page(request):
    return render(request,"users/user/login.html")


def user_profiles(request):
    user_names = User.objects.values_list('username', flat=True)
    return render(request, 'users/user/user_profiles.html', {'user_names': user_names})

templates/users/user/login.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Login Page</title>
    <link rel="stylesheet" href="{% static "css/login.css"%}">
</head>
<body class = "login-page">
    <div class="login-box-template">
        <h2 style="color: #a67c00;">JewelGleamers</h2>
        <form method="post" action = {% url "users:login" %}>
            {% csrf_token %}
            {% if messages %}
                {% for message in messages %}
                <p style="color: red;">{{ message }}</p>
                {% endfor %}
            {% endif %}
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" required>
            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required>
            <button type="submit">Login</button>
        </form>
     <div class="register-block">
        <a class="register" href="{% url 'users:register' %}">Not a User? Sign Up.</a>
    </div>
    </div>
</body>
</html>

templates/users/user/profile.html
{% extends "jewelGleamer/base.html" %}
{% load static %}
{% block page-title %}Profile Page{% endblock %}
<title>Profile Page</title>
{% block main-content %}
    <div class = "single-user-profile">
    <h2 class="user-profile"> Profile Page for {{ user.username }} </h2>
    {% if request.session.role == "Admin" or request.session.username == user.username %}
    <div class="profiles-page">
        <form id="profile-form" class="profile-form" action="{% url 'users:profile' username=user.username %}" method="post">
        {% csrf_token %}
        <label>Username</label> {{ user.username }}
        {% for field in form %}
        {% if field.name != 'role' %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                {{ field.errors }}
            </div>
        {% endif %}
    {% endfor %}
    {% if request.session.role == "Admin" %}
        <p style="font-size:small;font-style: italic;padding-left: 0.6rem">*Role can be either Admin or Regular*</p>
        <label for="{{ form.role.id_for_label }}">Role</label>
            {{ form.role }}
            {{ form.role.errors }}
    {% endif %}
        <div class="profile-save-button">
            <button type="submit" id="save-btn">Save</button>
        </div>
</form>
    </div>
        {% else %}
        <div class="else-profiles">
            <p class="profile-details">Username: {{ user.username }}</p>
            <p  class="profile-details">First Name: {{ user.first_name }}</p>
            <p  class="profile-details">Last Name: {{ user.last_name }}</p>
        </div>
    {% endif %}
       <div class="single-profile-feed">
           {% include "actions/action/feed.html" %}
       </div>
    </div>
{% endblock %}

templates/users/user/register.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Register Page</title>
    <link rel="stylesheet" href="{% static "css/login.css"%}">
</head>
<body class = "login-page">
    <div class="login-box-template">
        <h2 style="color: #a67c00;">JewelGleamers</h2>
        <form class="register-page" id="login-box" action="{% url "users:register" %}" method="POST">
        {% csrf_token %}
        {% if form.errors %}
            <div class="error">Registration failed. Please correct the errors below.</div>
        {% endif %}
        {{ form.as_div }}
        <input type="submit" name="submit" value="Register" class="register-button">
    </form>
        <div class="register-block">
            <a class="register" href="{% url 'users:login_page' %}">Login</a>
        </div>
    </div>
</body>
</html>

templates/users/user/user_profiles.html
{% extends "jewelGleamer/base.html" %}
{% load static %}
{% block page-title %}Users Profiles{% endblock %}
<title>User Profiles</title>
{% block main-content %}
    <div>
        <h2 class="user-profiles">User Profiles</h2>
        <div class="profile-list">
            {% for user_name in user_names %}
                <a href="{% url "users:profile" user_name %}" class="username-profile">
                    {{ user_name }}
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}