jewelGleamer/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'jewelGleamer'
urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.logged_user_home, name='logged_user_home'),
    path('blog/', views.blog, name='blog'),
    path('other_blogs/', views.other_blogs, name='other_blogs'),
    path('items/', views.jewelry_items_list, name='items_list'),
    path('items/<int:item_id>', views.jewelry_item_detail, name='item_detail'),
    path('items/<int:item_id>/delete_review/<int:review_id>/', views.delete_review, name='delete_review'),
    path('items/search', views.search, name='search'),
    path('items/add/', views.add_item, name='add_item'),
    path('items/<int:ring_id>/delete/', views.delete_ring, name='delete_ring'),
    path('items/<int:ring_id>/edit', views.edit_ring, name='edit_ring'),
    path('items/add_item/', views.add_new_item, name='add_new_item'),
    path('items/<int:item_id>/edit_review/<int:review_id>/', views.edit_review, name='edit_review'),
    path('generate_description/<int:item_id>/', views.generate_description, name='generate_description'),
    path('save_description/<int:item_id>/', views.save_description, name='save_description'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jewelGleamers/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jewelGleamer.urls', namespace='jewelGleamer')),
    path('users/', include('users.urls', namespace='users')),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('register', views.register, name='register'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('login_page',views.login_page, name="login_page"),
    path('userprofiles/', views.user_profiles, name='user_profiles'),
]

jewelGleamer/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


# Product class on the category page
class Product(models.Model):
    name = models.CharField(max_length=200)
    price = models.IntegerField(default=0)
    url = models.ImageField(upload_to='images/')
    author = models.CharField(default='Sindhu')
    date_posted = models.DateTimeField(default=timezone.now)
    details = models.TextField(default='Made in 14k solid gold, the alloy gives our pieces its beautiful, subtle hue. '
                                       'Band Thickness: 1.0 mm')
    description = models.TextField(default='The Stacker is the white tee of rings. It is everyone go-to because there '
                                           'is nothing it cant go with. This 14k solid gold essential is the perfect '
                                           'starter ring or addition to anyone collection.')
    materials = models.TextField(default='14k Solid Gold Our 14k solid gold pieces are made to last forever. 14k gold '
                                         'will not oxidize or discolor, so you can wear your jewelry every day.')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('jewelGleamer:item_detail', args=[self.id])


class Blogs(models.Model):
    description = models.TextField()


# Review Class
class Review(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    item = models.ForeignKey(Product, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.item.name

    def get_absolute_url(self):
        return reverse('jewelGleamer:item_detail', args=[self.item_id])


# Item Class for detailed view
class Item(models.Model):
    name = models.CharField(max_length=200)
    price = models.IntegerField(default=0)
    details = models.TextField()
    description = models.TextField()
    materials = models.TextField()
    urls = models.TextField()


# Image Class for urls
class Images(models.Model):
    url = models.CharField(max_length=200)


admin_user = {"username": "Admin", "password": "Admin"}
regular_user = {"username": "Sindhu", "password": "Sindhu"}

jewelGleamer/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['title', 'content']

jewelGleamer/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.urls import reverse
from .models import Review, Images, Product, Blogs
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from .forms import ReviewForm
from actions.models import Action
import openai
import random
import logging

openai.api_key = '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'


# Navigation to the home page when the user did not login to the page
def home(request):
    return render(request, "jewelGleamer/jewelry/index.html")


# Navigation to the home page when the user is logged in
def logged_user_home(request):
    image_list = Images.objects.all()
    actions = Action.objects.all().order_by('-created')
    return render(request, "jewelGleamer/jewelry/alternate.html",
                  {"images": image_list, "actions": actions})


# List of items in the item page
def jewelry_items_list(request):
    product_list = Product.objects.all().order_by('id')
    return render(request, "jewelGleamer/jewelry/category.html",
                  {"rings": product_list})


# Every item detail page
def jewelry_item_detail(request, item_id):
    item = get_object_or_404(Product, id=item_id)
    review_list = list(Review.objects.filter(item=item_id).order_by('-date_posted'))
    if request.method == 'POST':
        username = request.session.get('username')
        user = User.objects.get(username=username)
        content = request.POST.get('content', '')
        title = request.POST.get('title', '')
        review = Review.objects.create(author=user, title=title, content=content, item=item)
        review_title = review.title
        review_list.append(review)
        # log the action
        action = Action(
            user=user,
            verb="created a review " + review_title + " for the product ",
            target=item
        )
        action.save()

    review_list = Review.objects.filter(item=item_id).order_by('-date_posted')
    return render(request, "jewelGleamer/jewelry/item.html",
                  {"reviews": review_list, "item": item})


def edit_review(request, review_id, item_id):
    review = get_object_or_404(Review, id=review_id)
    review_title = review.title
    user = User.objects.get(username=request.session.get('username'))
    if request.method == 'POST':
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            form.save()
            # log the action
            action = Action(
                user=user,
                verb="edited a review with title " + review.title + " for the product",
                target=review
            )
            action.save()
            return redirect('jewelGleamer:item_detail', item_id=review.item.id)
    else:
        form = ReviewForm(instance=review)
    return render(request, "jewelGleamer/jewelry/edit_review.html", {"form": form, "review": review})


def delete_review(request, review_id, item_id):
    user = User.objects.get(username=request.session.get('username'))
    review = get_object_or_404(Review, id=review_id)
    review_title = review.title
    if request.session.get('username') == review.author.username or request.session.get('role') == 'Admin':
        # log the action
        action = Action(
            user=user,
            verb="deleted a review " + review_title,
            target=review
        )
        action.save()
        review.delete()
    return JsonResponse({'success': True, 'deleted_review_id': review_id})


# Adding an item to the category page of a product
def add_item(request):
    if request.method == 'POST':
        item_name = request.POST.get('item_name')
        item_price = request.POST.get('item_price')
        item_url = request.FILES['item_url'] if 'item_url' in request.FILES else None
        item_details = request.POST.get('item_details')
        item_description = request.POST.get('item_description')
        item_materials = request.POST.get('item_materials')
        user = User.objects.get(username=request.session.get('username'))
        new_product = Product(
            name=item_name,
            price=item_price,
            author=request.session.get('username'),
            details=item_details,
            description=item_description,
            materials=item_materials
        )
        product_name = new_product.name
        if item_url:
            new_product.url = item_url
        new_product.save()
        # log the action
        action = Action(
            user=user,
            verb="created a new product "+product_name+" : Link - ",
            target=new_product
        )
        action.save()
        messages.add_message(request, messages.SUCCESS, "You have successfully added product: %s" % new_product.name)
        return redirect('jewelGleamer:item_detail', item_id=new_product.id)
    product_list = Product.objects.all()
    return render(request, 'jewelGleamer/jewelry/category.html', {'rings': product_list})


# Deleting an item from the category page of a product
def delete_ring(request, ring_id):
    try:
        user = User.objects.get(username=request.session.get('username'))
        item_to_delete = Product.objects.get(id=ring_id)
        # log the action
        action = Action(
            user=user,
            verb="deleted the product : " + item_to_delete.name,
            target=item_to_delete
        )
        action.save()
        item_to_delete.delete()
        messages.add_message(request, messages.WARNING,
                             "You have successfully deleted product: %s" % item_to_delete.name)
    except Product.DoesNotExist:
        pass
    return redirect('jewelGleamer:items_list')


# Blog page view of the page where user can find other users blog
def blog(request):
    blogs_list = Blogs.objects.all()
    return render(request, "jewelGleamer/jewelry/blog.html", {"blogs": blogs_list})


# Searching the search bar on the header to navigate to the respective page
def search(request):
    search_input = request.GET.get('search-input', '').lower()
    product_list = Product.objects.all()
    blogs_list = Blogs.objects.all()
    if search_input == 'rings':
        return render(request, 'jewelGleamer/jewelry/category.html', {"rings": product_list})
    elif search_input == 'blogs':
        return render(request, 'jewelGleamer/jewelry/blog.html', {"blogs": blogs_list})
    else:
        return render(request, 'jewelGleamer/jewelry/search.html')


# Edit view to change item name and price on the category page for the product
def edit_ring(request, ring_id):
    product_list = Product.objects.get(id=ring_id)
    user = User.objects.get(username=request.session.get('username'))
    if request.method == 'POST':
        old_name = product_list.name
        old_price = product_list.price
        new_name = request.POST.get('new_name')
        new_price = request.POST.get('new_price')
        new_details = request.POST.get('new_details')
        new_description = request.POST.get('new_description')
        new_materials = request.POST.get('new_materials')
        if old_name != new_name:
            action_title = f"edited the title from '{old_name}' to '{new_name}': Link - "
            product_list.name = new_name
            action_title_instance = Action(
                user=user,
                verb=action_title,
                target=product_list
            )
            action_title_instance.save()
        if int(old_price) != int(new_price):
            action_price = f"edited the price from {old_price} to {new_price} : Link - "
            product_list.price = new_price
            action_price_instance = Action(
                user=user,
                verb=action_price,
                target=product_list
            )
            action_price_instance.save()
        product_list.name = new_name
        product_list.price = new_price
        product_list.details = new_details
        product_list.description = new_description
        product_list.materials = new_materials
        product_list.save()
        messages.add_message(request, messages.INFO, "You have successfully edited product: %s" % old_name)
        item_detail_url = reverse('jewelGleamer:item_detail', kwargs={'item_id': ring_id})
        return HttpResponseRedirect(item_detail_url)
    return render(request, 'jewelGleamer/jewelry/edit_product.html', {'product': product_list})


# Retrieving other blog posts in the blog page
def other_blogs(request):
    blogs = Blogs.objects.all()
    other_blog = [{'description': b.description} for b in blogs]
    return JsonResponse({'blogs': other_blog})


# Adding new item in the category page
def add_new_item(request):
    return render(request, 'jewelGleamer/jewelry/add_item.html')


# Generating AI related description for a product using description and materials.
def generate_description(request, item_id):
    try:
        item = get_object_or_404(Product, id=item_id)
        current_description = item.description
        item_details = item.details
        item_materials = item.materials
        prompt = request.POST.get('prompt', f"Provide an interesting description of the product: {current_description} using details: {item_details} and consider the item materials: {item_materials}. Limit the enhanced description to 2 lines please.")
        if not prompt:
            raise ValueError("Prompt cannot be empty.")
        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": "You are a helpful assistant."},
                {"role": "user", "content": prompt},
            ]
        )
        if 'choices' not in response or not response['choices']:
            raise ValueError("Failed to generate a description. Please try again.")
        choices = response['choices']

templates/jewelGleamer/jewelry/add_item.html
{% extends "jewelGleamer/base.html" %}
{% load static %}
{% block page-title %}Category Page{% endblock %}
{% block main-content %}
{% if request.session.username == 'Admin' %}
    <h2 class="edit-product">Add Product</h2>
    <div id="form-add" class="form-add">
            <form method="post" class = "form-add-inner" action="{% url 'jewelGleamer:add_item' %}" enctype="multipart/form-data">
                {% csrf_token %}
                <label class="add-item" for="item_name">Product Name:</label>
                <input class="input-item" type="text" name="item_name" required>
                <label class="add-item" for="item_price">Price:</label>
                <input class="input-item"  type="text" name="item_price" required>
                <label class="add-item" for="item_url">Image:</label>
                <input class="add-item" type="file" name="item_url">
                <label class="add-item" for="item_url">Details:</label>
                <input class="input-item" type="text" name="item_details" required >
                <label class="add-item" for="item_url">Description:</label>
                <input class="input-item" type="text" name="item_description" >
                <label class="add-item" for="item_url">Materials:</label>
                <input class="input-item" type="text" name="item_materials" required >
                <button type="submit" class = "add-submit-btn">Submit</button>
            </form>
        </div>
    {% endif %}
{% endblock %}

templates/jewelGleamer/jewelry/alternate.html
{% extends "jewelGleamer/base.html" %}
{% load static %}
{% block page-title %}Home Page{% endblock %}
{% block main-content %}
<div class="hero-text-button-a">
            <div class="hero-text-alternate">
                <div class="login-text">
                    <div class="purchase-container">
                        {% include "actions/action/feed.html" %}
                    </div>
                </div>
                <div class="continue-website">
                    <div class="hero-buttons">
                        <!-- Shop the collection that defaults to the Rings category page -->
                        <a class="hero-button" href="{% url 'jewelGleamer:items_list' %}">Shop the Collection</a>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

templates/jewelGleamer/jewelry/blog.html
{% extends "jewelGleamer/base.html" %}
{% load static %}
{% block page-title %}Blog Page{% endblock %}
{% block main-content %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static "js/script.js" %}"></script><script></script>
<div class="blog-post">
            <div class="other-posts">
                <!-- Other post details -->
                <div class="other-post-text">People's Experience with JewelGleamers</div>
                <div>
                    <button class="other-blogs">View</button>
                </div>
                <div>
                    <button class="hide-blogs" style="display: none;">Hide</button>
                </div>
                <div class="post-details"></div>
            </div>
        </div>
{% endblock %}

templates/jewelGleamer/jewelry/category.html
{% extends "jewelGleamer/base.html" %}
{% load static %}
{% block page-title %}Category Page{% endblock %}
{% block main-content %}
    <div class="navigation-bar">
            <!-- Category selected -->
            <div class="head-title">
                <h2>RINGS</h2>
            </div>
            <div class="paragraph">You’ve got an edge—your rings should too.</div>
        </div>
    <div class="add">
    <div class=" filter">
         {% if rings %}
            <button class="filter-button" id="sort-by-price" onclick="sortByPrice()">SORT BY PRICE</button>
        {% endif %}
        </div>
    {% if request.session.username == 'Admin' %}
            <a class="add-product" href="{% url 'jewelGleamer:add_new_item'%}">Add New Product</a>
    {% endif %}
    </div>
    {% if rings %}
        <div id="wishlist-message" class="alert alert-success" style="display: none;"></div>
        <div class="grid-images"  id="item-container">
            <!-- Various images of the product, name and price of the product -->
            {% for ring in rings %}
               <div class="image-containers" data-price="{{ ring.price }}">
               {% if request.session.username == 'Admin' %}
               <div class = "delete-div">
                   <a class="edit-details-link" href="{% url 'jewelGleamer:edit_ring' ring.id %}">Edit</a>
                <form  class="delete-form" method="post" action="{% url 'jewelGleamer:delete_ring' ring.id %}">
                {% csrf_token %}
                <input type="hidden" name="ring_id" value="{{ ring.id }}">
                <button class="delete-product" type="button" onclick="confirmDelete('{{ ring.id }}')">Delete</button>
                </form>
                </div>
               {% endif %}
               {% if ring.url %}
                   <a href="{% url 'jewelGleamer:item_detail' ring.id %}"><img class="ring-image" src="{{ ring.url.url  }} " alt="Ring DEF"></a>
               {% else %}
                   <a href="{% url 'jewelGleamer:item_detail' ring.id %}"><img class="ring-image" src="{% static 'ring1.jpeg' %}" alt="Ring 1"></a>
               {% endif %}
                <div class="wishlist-text">
                    <div class="text">
                        <div class="ring-type">{{ ring.name }}</div>
                        <div>${{ ring.price }}</div>
                    </div>
                </div>
               </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="no-products">
        There are no products right now. Click on Add New Product button to proceed further!
        </div>
    {% endif %}
{% endblock %}

templates/jewelGleamer/jewelry/edit_review.html
{% extends "jewelGleamer/base.html" %}
{% load static %}
{% block page-title %}Edit Review{% endblock %}

{% block main-content %}
  <h3 class="edit-review">Edit Review</h3>
  <form class="edit-review-form" method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save Changes</button>
  </form>
{% endblock %}

templates/jewelGleamer/jewelry/item.html
{% extends "jewelGleamer/base.html" %}
{% load static %}
{% load tz %}
{% block page-title %}Item Page{% endblock %}
{% block main-content %}
<div class="ring-preview">
            <!-- Single item review of the page -->
            <div class="image-preview">
                {% if item.url %}
                <!-- Left side view of the images -->
                <div class="box-preview"><img src="{% static 'images/ring1_view1.jpeg' %}" alt="Ring 4"></div>
                <div class="box-preview"><img src="{{ item.url.url }}" alt="Ring 4"></div>
                <div class="box-preview"><img src="{% static 'images/ring1_view3.jpeg' %}" alt="Ring 4"></div>
               {% endif %}
           </div>
            <div class="main-image-preview">
                <!-- Main image to display on the single product page -->
                {% if item.url %}
                <div class="box-preview"><img src="{{ item.url.url }}" alt="Ring 4"></div>
               {% else %}
                 <div class="box-preview"><img src="{% static 'images/ring1.jpeg' %}" alt="Ring 4"></div>
               {% endif %}
            </div>
            <div class="ring-text">
                <!-- Name and price of the product -->
                <div class="details-edit">
                    <div class="ring-name">{{ item.name }}</div>
                    {% if request.session.username == 'Admin' %}
                        <a class="edit-details-page" href="{% url 'jewelGleamer:edit_ring' item.id %}">Edit Details</a>
                    {% endif %}
                </div>
                <div class="ring-price">${{ item.price }}</div>
                    <div class="ring-post">Posted by {{ item.author }} on
                        {{ item.date_posted|timezone:"US/Eastern"|date:"F j, Y P" }}</div>
                <div class="rating-review">
                    <div>
                        <!-- overall rating of the product -->
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star-half-o" aria-hidden="true"></i>
                    </div>
                    <div class="rating">
                        <div>4.5 | </div>
                        <!-- Redirects to the review page -->
                        <a href="#review-section" class="review">See 42 reviews</a>
                    </div>
                </div>
                <div class="rating-review">
                    <!-- Product specifications of the page -->
                    <div>Ring Size </div>
                </div>
                <div class="ring-sizes">
                    <input type="radio" class = "radio-size" name="ring-size" id="size5">
                    <label for="size5">5</label>

                    <input type="radio" class = "radio-size" name="ring-size" id="size6">
                    <label for="size6">6</label>

                    <input type="radio"class = "radio-size" name="ring-size" id="size7">
                    <label for="size7">7</label>

                    <input type="radio" class = "radio-size" name="ring-size" id="size8">
                    <label for="size8">8</label>

                    <input type="radio" class = "radio-size" name="ring-size" id="size9">
                    <label for="size9">9</label>

                    <input type="radio" class = "radio-size" name="ring-size" id="size10">
                    <label for="size10">10</label>
                </div>
                <div class="add-to-bag">
                    <!-- Add to either wishlist or bag -->
                    <button class="add-bag-page">ADD TO BAG</button>
                </div>
                <div id="text-successful"></div>
                <div class="grid-details">
                    <!-- Specifications or Reviews of the product -->
                    <a href="#details" class="review">Specifications</a>
                    <a href="#review-section" class="review">Reviews</a>
                </div>
            </div>
        </div>
    <div class="dmd" id="details">
        <div class="reviews">DETAILS</div>
        <!-- Details of the product -->
        <div>{{ item.details}}</div>
    </div>
    <div class="dmd" id="description">
        <!-- Description of the product -->
        <div class="reviews">DESCRIPTION</div>
        <div class = "description-new">{{ item.description }}</div>
        {% if request.session.role == 'Admin' %}
        <div class = "prompt-placeholder"> This is a Prompt that will be sent to AI, We have given a sample prompt, change it if you would like to: </div>
        <textarea class = "prompt" style="display: block;">Provide an interesting description of the product: {{ item.description }} using details: {{ item.details }} and consider the item materials: {{item.materials}} Limit the enhanced description to 2 lines please </textarea>
            <div class = "prompt-error"></div>
            <div id="rate-limit-error" style="color: red; display: none;">Rate limit reached. Please try again after a short wait of 1 minute.</div>
        <div class = "generate-placeholder" style="display: none;"> This is the Generated Response from AI. Please Save if you like it, or generate a new response</div>
        <textarea id="description-edit" style="display: none;">{{ item.description }}</textarea>
            <div class = "description-error"></div>
        <div class = "description-flex-edit">
        <div><button class="generate-description" data-itemid="{{ item.id }}">Generate Enhanced Description</button></div>
        <div><button id="save-description" data-itemid="{{ item.id }}" style="display: none;">Save Description</button></div>
            <div><button id="cancel-description" data-itemid="{{ item.id }}" style="display: none;">Cancel</button></div>
        </div>
        {% endif %}
    </div>
    <div class="dmd" id="materials">
        <!-- Materials used in the product -->
        <div class="reviews">MATERIALS</div>
        <div>{{ item.materials }}
        </div>
    </div>
    <div class="review-section" id="review-section">
        <!-- Review section of the product -->
        <div class="reviews">REVIEWS</div>
        <div class="review-box">
            <div class="review-item">
                <div class="review-ratings">
                    <div>
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star-half-o" aria-hidden="true"></i>
                    </div>
                    <div class="review-rating">
                        <div>4.5 | </div>
                        <div> 42 Reviews</div>
                    </div>
                </div>
            </div>
            {% if request.session.username %}
            <div class="review-item">
                <!-- Review the product -->
                <button class="ask-question">REVIEW THIS PRODUCT</button>
            </div>
    {% endif %}
        </div>
    <form class="form-review-details" style="display: none;">
                {% csrf_token %}
                    <input type="hidden" name="review_id" value="{{ review.id }}">
                    <label class="add-item" for="title">Title:</label>
                    <input type="text" name="title" required />
                    <label class="add-item" for="content">Content:</label>
                    <textarea name="content" rows="5" required></textarea>
                    <input type="hidden" name="rings_id" value= {{ item.id }} />
        <div>
            <button type="submit">Post Review</button>
        </div>
                </form>
        <div class="review-questions">
            <div class="review-details">
            {% if reviews %}
                {% for review in reviews %}
                    <div class = "review-new-div">
                    <div class="review-discussion">
                    <div class="review-discussion-lister">
                        <a href="{% url 'users:profile' review.author %}">
                        {{ review.author }}
                    </a></div>
                    <div>
                        <div class="review-discussion-stars">
                            <i class="fa fa-star rex" aria-hidden="true"></i>
                            <i class="fa fa-star rex" aria-hidden="true"></i>
                            <i class="fa fa-star rex" aria-hidden="true"></i>
                            <i class="fa fa-star rex" aria-hidden="true"></i>
                            <i class="fa fa-star-half-o rex" aria-hidden="true"></i>
                        </div>
                        <div class="review-discussion-title">{{ review.title}}
                        </div>
                        <div class="review-discussion-content">{{ review.content }}</div>
                        {{ review.date_posted|timezone:"US/Eastern"|date:"F j, Y P" }}
                    </div>
                        {% if request.session.role == 'Admin' or request.session.username == review.author.username %}
                        <div class="review-actions">
                        <a class="review-edit-delete" href="{% url 'jewelGleamer:edit_review' item_id=item.id review_id=review.id %}">Edit</a>
                        <a class="review-delete-new" data-itemid="{{ item.id }}" data-reviewid ="{{ review.id }}" href="#">Delete</a>
                         </div>
                        {% endif %}
                </div>
                    </div>
                {% endfor %}
              {% else %}
                <div class="no-comments">
                    <p>No comments for this product yet!</p>
                </div>
    {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/jewelGleamer/jewelry/search.html
{% extends "jewelGleamer/base.html" %}
{% load static %}

{% block main-content %}
    <div class="search">
      <h1>NO SEARCH RESULTS FOUND</h1>
        <p>Navigate back to the <a style="text-decoration: underline;color:blue" href="{% url 'jewelGleamer:home' %}">home page</a> and try finding other
            results.</p>
    </div>
{% endblock %}